# Generated by Django 2.0.7 on 2018-07-17 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('time', models.CharField(max_length=10)),
                ('current', models.IntegerField(default=1)),
                ('maximum', models.IntegerField(default=5)),
            ],
        ),
    ]
